version: "3.8"

services:
  fastapi-app:
    image: kennethan/fastapi-app-prime:latest
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
